"""
/////////////
/// STATS ///
/////////////
"""

MAXHP_STATKEY = 'MAXHP'
HP_STATKEY = 'HP'
MAXMP_STATKEY = 'MAXMP'
MP_STATKEY = 'MP'
ATK_STATKEY = 'ATK'
DEF_STATKEY = 'DEF'
MATK_STATKEY = 'MATK'
MDEF_STATKEY = 'MDEF'
SPEED_STATKEY = 'SPEED'
CRITCH_STATKEY = 'CRITCH'
CRITDMG_STATKEY = 'CRITDMG'

INITIAL_STATS = {MAXHP_STATKEY: 25,
                 HP_STATKEY: 25,
                 MAXMP_STATKEY: 10,
                 MP_STATKEY: 10,
                 ATK_STATKEY: 10,
                 DEF_STATKEY: 10,
                 MATK_STATKEY: 10,
                 MDEF_STATKEY: 10,
                 SPEED_STATKEY: 10,
                 CRITCH_STATKEY: 10,
                 CRITDMG_STATKEY: 10
                 }
STAT_NAMES = [MAXHP_STATKEY, HP_STATKEY, MAXMP_STATKEY, MP_STATKEY, ATK_STATKEY, DEF_STATKEY,
              MATK_STATKEY, MDEF_STATKEY, SPEED_STATKEY, CRITCH_STATKEY, CRITDMG_STATKEY]

"""
/////////////
/// ITEMS ///
/////////////
"""

EQUIPMENT_NAMES = ['HELMET', 'ARMOR', 'WEAPON', 'ACCESSORY']
WEAPON_NAMES = ["SWORD", "AXE", "SPEAR", "DAGGER", "STAFF", "BOW"]

"""
///////////////
/// OPTIONS ///
///////////////
"""

FULLY_RECOVER_WHEN_LEVELING_UP = True
STAT_UPGRADE_WHEN_LEVELING_UP = 1
POSSIBLE_PLAYER_ACTIONS = ["NORMAL_ATTACK", "SKILL"]

"""
////////////
/// JOBS ///
////////////
"""

INITIAL_JOB_DICT = {"Name": "Novice", "lvl": 1, "xp": 0}

"""
////////////
/// SKILLS ///
////////////
"""

SKILL_TYPE_DMG = "DAMAGING_MAGIC"
SKILL_TYPE_HEAL = "HEALING_MAGIC"

"""
////////////
/// JSON ///
////////////
"""

AREAS_KEYS = ["NAME", "NUMBER", "ENEMY_LIST", "BOSS", "DUNGEONS"]
DUNGEON_KEYS = []
ENEMY_KEYS = ["NAME", "STATS", "XP_REWARD", "GOLD_REWARD", "POSSIBLE_LOOT", "LOOT_CHANCE", "SKILLS", "IMAGE_URL", "IS_BOSS"]
EQUIPMENT_KEYS = ["NAME", "DESCRIPTION", "INDIV_VALUE", "OBJECT_TYPE", "EQUIPMENT_TYPE", "STAT_CHANGE_LIST"]
ITEM_KEYS = ["NAME", "DESCRIPTION", "INDIV_VALUE", "OBJECT_TYPE"]
JOB_KEYS = ["NAME", "DESCRIPTION", "SKILL_DICT", "XP_FACTOR"]
SHOP_KEYS = ["AREA_NUMBER", "ITEM_LIST"]
SKILL_KEYS = ["NAME", "DESCRIPTION", "MP_COST", "TYPE", "POWER", "ELEMENT", "STATUS_EFFECT", "ACTIVATION_TIMES"]
